export const NODE_SERVER_URL = "http://localhost:8080/"
export const PYTHON_SERVER_URL = "http://localhost:7070/"
export const RUBY_SERVER_URL = "http://localhost:6060/"
export const GO_SERVER_URL = "http://localhost:5050/"
export const PHP_SERVER_URL = "http://localhost:4040/"